name: Auto Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ssc1baju4486@sc1baju4486.universe.wf "
          cd /home/sc1baju4486/repositories/py
          git pull origin main
        "
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      
